// Expanded Emoji Library
export const COMMON_EMOJIS = [
    // Celebration
    { char: '🎉', keywords: 'party, celebrate, event, general, confetti', category: 'Celebration' },
    { char: '🎂', keywords: 'birthday, cake, celebrate, age', category: 'Celebration' },
    { char: '💍', keywords: 'anniversary, wedding, ring, love, marriage, proposal, engagement', category: 'Celebration' },
    { char: '🎊', keywords: 'party, celebration, ball', category: 'Celebration' },
    { char: '🎈', keywords: 'balloon, party, celebrate', category: 'Celebration' },
    { char: '🎆', keywords: 'fireworks, celebrate, new year, 4th of july', category: 'Celebration' },
    { char: '🎇', keywords: 'sparkler, celebrate', category: 'Celebration' },
    { char: '🥂', keywords: 'cheers, celebrate, drink, toast, champagne', category: 'Celebration' },
    { char: '🍾', keywords: 'bottle, bubbly, drink', category: 'Celebration' },
    { char: '🍰', keywords: 'cake, food, celebrate, dessert', category: 'Celebration' },
    { char: '🧁', keywords: 'cupcake, food, dessert', category: 'Celebration' },
    { char: '🎁', keywords: 'gift, present, christmas, birthday', category: 'Celebration' },
    { char: '🧧', keywords: 'red envelope, money, luck, new year', category: 'Celebration' },
    { char: '🥳', keywords: 'party face, celebrate, happy', category: 'Celebration' },
    { char: '🕯️', keywords: 'candle', category: 'Celebration' },
    { char: '🏮', keywords: 'red lantern', category: 'Celebration' },
    { char: '🎋', keywords: 'tanabata tree', category: 'Celebration' },
    { char: '🎍', keywords: 'pine decoration', category: 'Celebration' },
    { char: '🎎', keywords: 'japanese dolls', category: 'Celebration' },
    { char: '🎏', keywords: 'carp streamer', category: 'Celebration' },
    { char: '🎐', keywords: 'wind chime', category: 'Celebration' },
    { char: '🎑', keywords: 'moon viewing ceremony', category: 'Celebration' },
    { char: '🎟️', keywords: 'admission tickets', category: 'Celebration' },
    { char: '🎫', keywords: 'ticket', category: 'Celebration' },
    { char: '🎖️', keywords: 'military medal', category: 'Celebration' },
    { char: '🏆', keywords: 'trophy', category: 'Celebration' },
    { char: '🏅', keywords: 'sports medal', category: 'Celebration' },
    { char: '🥇', keywords: '1st place medal', category: 'Celebration' },
    { char: '🥈', keywords: '2nd place medal', category: 'Celebration' },
    { char: '🥉', keywords: '3rd place medal', category: 'Celebration' },
    { char: '🪄', keywords: 'magic wand', category: 'Celebration' },

    // Holidays
    { char: '🎃', keywords: 'pumpkin, halloween, jack-o-lantern, spooky, autumn, holiday', category: 'Holidays' },
    { char: '👻', keywords: 'ghost, halloween, spooky, scare, spirit', category: 'Holidays' },
    { char: '🧛', keywords: 'vampire, halloween, dracula, monster', category: 'Holidays' },
    { char: '🧟', keywords: 'zombie, halloween, undead, monster', category: 'Holidays' },
    { char: '🎄', keywords: 'tree, christmas, xmas, holiday, winter, pine, decoration', category: 'Holidays' },
    { char: '🎅', keywords: 'santa, christmas, claus, father christmas, holiday', category: 'Holidays' },
    { char: '🤶', keywords: 'mrs claus, christmas, holiday, santa', category: 'Holidays' },
    { char: '☃️', keywords: 'snowman, winter, snow, christmas, cold, ice', category: 'Holidays' },
    { char: '❄️', keywords: 'snowflake, winter, cold, snow, ice, weather', category: 'Holidays' },
    { char: '🦃', keywords: 'turkey, thanksgiving, bird, food, animal, holiday', category: 'Holidays' },
    { char: '🐰', keywords: 'rabbit, easter, bunny, animal, pet', category: 'Holidays' },
    { char: '🐣', keywords: 'chick, easter, baby, bird, animal', category: 'Holidays' },
    { char: '💘', keywords: 'heart, love, valentine, cupid, arrow, romance', category: 'Holidays' },
    { char: '💝', keywords: 'heart, gift, love, valentine, ribbon, present', category: 'Holidays' },
    { char: '🧨', keywords: 'firecracker, new year, celebration, red', category: 'Holidays' },
    { char: '☘️', keywords: 'shamrock, st patrick, luck, irish, green, plant', category: 'Holidays' },
    { char: '🍀', keywords: 'clover, luck, st patrick, four leaf, plant', category: 'Holidays' },

    // Arts & Activities
    { char: '🎨', keywords: 'art, palette, paint, draw, artist, color, design, easel', category: 'Arts' },
    { char: '🖼️', keywords: 'frame, picture, art, museum, painting, easel', category: 'Arts' },
    { char: '🎭', keywords: 'theater, masks, drama, art, acting, performance', category: 'Arts' },
    { char: '🎪', keywords: 'circus, tent, carnival, fair', category: 'Arts' },
    { char: '💃', keywords: 'dancer, woman, salsa, party, fun, dress, dancing', category: 'Arts' },
    { char: '🕺', keywords: 'dancer, man, disco, party, fun, dancing', category: 'Arts' },
    { char: '👯', keywords: 'dancers, bunny ears, party, friends, dancing', category: 'Arts' },
    { char: '🩰', keywords: 'ballet, shoes, dance, ballerina, dancing', category: 'Arts' },
    { char: '🎤', keywords: 'microphone, sing, karaoke, music, audio', category: 'Arts' },
    { char: '🎧', keywords: 'headphones, music, listen, audio', category: 'Arts' },
    { char: '🎼', keywords: 'score, music, clef, notes', category: 'Arts' },
    { char: '🎹', keywords: 'piano, music, instrument, keyboard', category: 'Arts' },
    { char: '🥁', keywords: 'drum, music, instrument, beat', category: 'Arts' },
    { char: '🎷', keywords: 'saxophone, music, instrument, jazz', category: 'Arts' },
    { char: '🎺', keywords: 'trumpet, music, instrument, brass', category: 'Arts' },
    { char: '🎸', keywords: 'guitar, music, instrument, rock', category: 'Arts' },
    { char: '🪕', keywords: 'banjo, music, instrument, folk', category: 'Arts' },
    { char: '🎻', keywords: 'violin, music, instrument, string', category: 'Arts' },
    { char: '🎬', keywords: 'clapper, movie, film, cinema, action', category: 'Arts' },
    { char: '🎮', keywords: 'game, controller, play, video game, console', category: 'Arts' },
    { char: '👾', keywords: 'alien, monster, game, retro, space invader', category: 'Arts' },
    { char: '🎰', keywords: 'slot machine, casino, game, luck, gamble', category: 'Arts' },
    { char: '🎲', keywords: 'die, dice, game, luck, random, board game', category: 'Arts' },
    { char: '♟️', keywords: 'pawn, chess, game, strategy, board game', category: 'Arts' },

    // Travel
    { char: '✈️', keywords: 'trip, travel, flight, plane, vacation', category: 'Travel' },
    { char: '🛫', keywords: 'departure, takeoff, flight', category: 'Travel' },
    { char: '🛬', keywords: 'arrival, landing, flight', category: 'Travel' },
    { char: '🏖️', keywords: 'beach, vacation, summer, holiday, sand', category: 'Travel' },
    { char: '🏝️', keywords: 'island, vacation, tropical', category: 'Travel' },
    { char: '🏔️', keywords: 'mountain, snow, hiking, trip', category: 'Travel' },
    { char: '🏕️', keywords: 'camping, tent, outdoors', category: 'Travel' },
    { char: '🏠', keywords: 'home, house, move, address', category: 'Travel' },
    { char: '🏢', keywords: 'office, work, building', category: 'Travel' },
    { char: '🚗', keywords: 'car, drive, trip, road', category: 'Travel' },
    { char: '🚂', keywords: 'train, trip, travel', category: 'Travel' },
    { char: '🛳️', keywords: 'cruise, ship, boat, vacation', category: 'Travel' },
    { char: '🌍', keywords: 'world, earth, global, travel', category: 'Travel' },
    { char: '🗽', keywords: 'statue, nyc, travel', category: 'Travel' },
    { char: '🗼', keywords: 'tokyo, paris, tower', category: 'Travel' },
    { char: '🎡', keywords: 'ferris wheel, park, fair', category: 'Travel' },
    { char: '🎢', keywords: 'roller coaster, park', category: 'Travel' },
    { char: '🏨', keywords: 'hotel, travel, stay', category: 'Travel' },
    { char: '🌋', keywords: 'volcano, nature', category: 'Travel' },
    { char: '🗺️', keywords: 'map, travel, plan', category: 'Travel' },
    { char: '🚲', keywords: 'bike, travel, cycle', category: 'Travel' },
    { char: '🚕', keywords: 'taxi, car, city', category: 'Travel' },
    { char: '🎒', keywords: 'backpack, travel, hiking', category: 'Travel' },

    // Education
    { char: '✏️', keywords: 'exam, study, school, test, write', category: 'Education' },
    { char: '🎓', keywords: 'graduation, school, education, degree', category: 'Education' },
    { char: '📚', keywords: 'books, study, read, school', category: 'Education' },
    { char: '📝', keywords: 'notes, writing, test', category: 'Education' },
    { char: '🏫', keywords: 'school, university', category: 'Education' },
    { char: '🍎', keywords: 'apple, teacher, school', category: 'Education' },
    { char: '🧠', keywords: 'brain, study, thinking', category: 'Education' },
    { char: '📐', keywords: 'ruler, math, school', category: 'Education' },
    { char: '🧪', keywords: 'science, lab, experiment', category: 'Education' },
    { char: '🔬', keywords: 'microscope, science', category: 'Education' },
    { char: '🔭', keywords: 'telescope, space, science', category: 'Education' },

    // Work
    { char: '💻', keywords: 'computer, work, tech, laptop', category: 'Work' },
    { char: '💼', keywords: 'work, business, job, briefcase', category: 'Work' },
    { char: '🖥️', keywords: 'desktop, work, computer', category: 'Work' },
    { char: '📊', keywords: 'chart, work, presentation', category: 'Work' },
    { char: '🖋️', keywords: 'pen, write, work', category: 'Work' },
    { char: '📅', keywords: 'calendar, date, schedule, work', category: 'Work' },
    { char: '📎', keywords: 'clip, office, work', category: 'Work' },
    { char: '🖇️', keywords: 'clips, office', category: 'Work' },

    // Sports
    { char: '⚽', keywords: 'soccer ball', category: 'Sports' },
    { char: '⚾', keywords: 'baseball', category: 'Sports' },
    { char: '🥎', keywords: 'softball', category: 'Sports' },
    { char: '🏀', keywords: 'basketball', category: 'Sports' },
    { char: '🏐', keywords: 'volleyball', category: 'Sports' },
    { char: '🏈', keywords: 'american football', category: 'Sports' },
    { char: '🏉', keywords: 'rugby football', category: 'Sports' },
    { char: '🎾', keywords: 'tennis', category: 'Sports' },
    { char: '🥏', keywords: 'flying disc', category: 'Sports' },
    { char: '🎳', keywords: 'bowling', category: 'Sports' },
    { char: '🏏', keywords: 'cricket game', category: 'Sports' },
    { char: '🏑', keywords: 'field hockey', category: 'Sports' },
    { char: '🏒', keywords: 'ice hockey', category: 'Sports' },
    { char: '🥍', keywords: 'lacrosse', category: 'Sports' },
    { char: '🏓', keywords: 'ping pong', category: 'Sports' },
    { char: '🏸', keywords: 'badminton', category: 'Sports' },
    { char: '🥊', keywords: 'boxing glove', category: 'Sports' },
    { char: '🥋', keywords: 'martial arts uniform', category: 'Sports' },
    { char: '🥅', keywords: 'goal net', category: 'Sports' },
    { char: '⛳', keywords: 'flag in hole', category: 'Sports' },
    { char: '⛸️', keywords: 'ice skate', category: 'Sports' },
    { char: '🎣', keywords: 'fishing pole', category: 'Sports' },
    { char: '🤿', keywords: 'diving mask', category: 'Sports' },
    { char: '🎽', keywords: 'running shirt', category: 'Sports' },
    { char: '🎿', keywords: 'skis', category: 'Sports' },
    { char: '🛷', keywords: 'sled', category: 'Sports' },
    { char: '🥌', keywords: 'curling stone', category: 'Sports' },
    { char: '🎯', keywords: 'bullseye', category: 'Sports' },
    { char: '🏁', keywords: 'race, finish, end, start', category: 'Sports' },
    { char: '🏃', keywords: 'run, race, fitness, sports, exercise', category: 'Sports' },
    { char: '🚴', keywords: 'bike, cycle, fitness, sports', category: 'Sports' },
    { char: '🏋️', keywords: 'weight, gym, lifting', category: 'Sports' },
    { char: '🧘', keywords: 'yoga, zen, meditation', category: 'Sports' },
    { char: '🏌️', keywords: 'golf, sports', category: 'Sports' },
    { char: '🏄', keywords: 'surf, water, sports', category: 'Sports' },
    { char: '🏊', keywords: 'swim, water, sports', category: 'Sports' },
    { char: '🛹', keywords: 'skateboard, fun', category: 'Sports' },

    // Health
    { char: '🏥', keywords: 'hospital, health, doctor, medical', category: 'Health' },
    { char: '💊', keywords: 'pill, medicine, health', category: 'Health' },
    { char: '💉', keywords: 'injection, vaccine, health', category: 'Health' },
    { char: '🦷', keywords: 'dentist, tooth, health', category: 'Health' },
    { char: '🩺', keywords: 'stethoscope, doctor, health', category: 'Health' },
    { char: '🩹', keywords: 'bandage, health', category: 'Health' },
    { char: '🩸', keywords: 'blood, health', category: 'Health' },
    { char: '🧬', keywords: 'dna, health, science', category: 'Health' },

    // Life
    { char: '🍼', keywords: 'baby, bottle, new', category: 'Life' },
    { char: '👶', keywords: 'baby, child, born', category: 'Life' },
    { char: '🤰', keywords: 'pregnant, pregnancy, baby', category: 'Life' },
    { char: '🤱', keywords: 'breastfeeding, baby', category: 'Life' },
    { char: '🛌', keywords: 'sleep, rest', category: 'Life' },
    { char: '🧼', keywords: 'soap, clean', category: 'Life' },

    // Food
    { char: '🍕', keywords: 'pizza, food, party', category: 'Food' },
    { char: '🍔', keywords: 'burger, food', category: 'Food' },
    { char: '🌮', keywords: 'taco, food', category: 'Food' },
    { char: '🍣', keywords: 'sushi, food', category: 'Food' },
    { char: '🍜', keywords: 'ramen, food', category: 'Food' },
    { char: '🍦', keywords: 'ice cream, dessert', category: 'Food' },
    { char: '🍩', keywords: 'donut, dessert', category: 'Food' },
    { char: '☕', keywords: 'coffee, morning, tea', category: 'Food' },
    { char: '🍺', keywords: 'beer, drink, party', category: 'Food' },
    { char: '🍷', keywords: 'wine, drink, dinner', category: 'Food' },
    { char: '🍸', keywords: 'cocktail, drink', category: 'Food' },
    { char: '🥪', keywords: 'sandwich, food', category: 'Food' },
    { char: '🥗', keywords: 'salad, food, healthy', category: 'Food' },
    { char: '🥞', keywords: 'pancakes, breakfast', category: 'Food' },
    { char: '🍳', keywords: 'egg, breakfast', category: 'Food' },
    { char: '🥐', keywords: 'croissant, bread', category: 'Food' },
    { char: '🥯', keywords: 'bagel, bread', category: 'Food' },
    { char: '🥨', keywords: 'pretzel, snack', category: 'Food' },
    { char: '🥖', keywords: 'baguette, bread', category: 'Food' },
    { char: '🧀', keywords: 'cheese, food', category: 'Food' },
    { char: '🥚', keywords: 'egg, food', category: 'Food' },
    { char: '🥓', keywords: 'bacon, breakfast', category: 'Food' },
    { char: '🥩', keywords: 'steak, meat', category: 'Food' },
    { char: '🍗', keywords: 'poultry, chicken', category: 'Food' },
    { char: '🍖', keywords: 'meat on bone', category: 'Food' },
    { char: '🌭', keywords: 'hot dog', category: 'Food' },
    { char: '🍟', keywords: 'french fries', category: 'Food' },
    { char: '🍿', keywords: 'popcorn, movie', category: 'Food' },
    { char: '🧈', keywords: 'butter', category: 'Food' },
    { char: '🧂', keywords: 'salt', category: 'Food' },
    { char: '🥫', keywords: 'canned food', category: 'Food' },
    { char: '🍱', keywords: 'bento box', category: 'Food' },
    { char: '🍘', keywords: 'rice cracker', category: 'Food' },
    { char: '🍙', keywords: 'rice ball', category: 'Food' },
    { char: '🍚', keywords: 'cooked rice', category: 'Food' },
    { char: '🍛', keywords: 'curry rice', category: 'Food' },
    { char: '🍢', keywords: 'oden', category: 'Food' },
    { char: '🍡', keywords: 'dango', category: 'Food' },
    { char: '🍧', keywords: 'shaved ice', category: 'Food' },
    { char: '🍨', keywords: 'ice cream', category: 'Food' },
    { char: '🥧', keywords: 'pie', category: 'Food' },
    { char: '🍫', keywords: 'chocolate bar', category: 'Food' },
    { char: '🍬', keywords: 'candy', category: 'Food' },
    { char: '🍭', keywords: 'lollipop', category: 'Food' },
    { char: '🍮', keywords: 'custard', category: 'Food' },
    { char: '🍯', keywords: 'honey pot', category: 'Food' },
    { char: '🧃', keywords: 'beverage box', category: 'Food' },
    { char: '🥤', keywords: 'cup with straw', category: 'Food' },
    { char: '🧋', keywords: 'bubble tea', category: 'Food' },
    { char: '🧉', keywords: 'mate', category: 'Food' },
    { char: '🧊', keywords: 'ice cube', category: 'Food' },
    { char: '🥢', keywords: 'chopsticks', category: 'Food' },
    { char: '🍽️', keywords: 'fork and knife with plate', category: 'Food' },
    { char: '🍴', keywords: 'fork and knife', category: 'Food' },
    { char: '🥄', keywords: 'spoon', category: 'Food' },

    // Nature
    { char: '🌸', keywords: 'flower, spring, cherry blossom', category: 'Nature' },
    { char: '💮', keywords: 'white flower', category: 'Nature' },
    { char: '🏵️', keywords: 'rosette', category: 'Nature' },
    { char: '🌹', keywords: 'rose, flower', category: 'Nature' },
    { char: '🥀', keywords: 'wilted flower', category: 'Nature' },
    { char: '🌺', keywords: 'hibiscus, flower', category: 'Nature' },
    { char: '🌻', keywords: 'sunflower, summer', category: 'Nature' },
    { char: '🌼', keywords: 'blossom, flower', category: 'Nature' },
    { char: '🌷', keywords: 'tulip, flower', category: 'Nature' },
    { char: '🌱', keywords: 'seedling', category: 'Nature' },
    { char: '🪴', keywords: 'potted plant', category: 'Nature' },
    { char: '🌲', keywords: 'evergreen tree', category: 'Nature' },
    { char: '🌳', keywords: 'deciduous tree', category: 'Nature' },
    { char: '🌴', keywords: 'palm tree', category: 'Nature' },
    { char: '🌵', keywords: 'cactus', category: 'Nature' },
    { char: '🌾', keywords: 'sheaf of rice', category: 'Nature' },
    { char: '🌿', keywords: 'herb', category: 'Nature' },
    { char: '🍁', keywords: 'maple leaf, autumn', category: 'Nature' },
    { char: '🍂', keywords: 'fallen leaf, autumn', category: 'Nature' },
    { char: '🍃', keywords: 'leaf fluttering in wind', category: 'Nature' },
    { char: '🍄', keywords: 'mushroom', category: 'Nature' },
    { char: '🐚', keywords: 'spiral shell', category: 'Nature' },
    { char: '☀️', keywords: 'sun, sunny, day, hot, weather', category: 'Nature' },
    { char: '⭐', keywords: 'star', category: 'Nature' },
    { char: '🌟', keywords: 'glowing star', category: 'Nature' },
    { char: '🌠', keywords: 'shooting star', category: 'Nature' },
    { char: '🌌', keywords: 'milky way', category: 'Nature' },
    { char: '🔥', keywords: 'fire', category: 'Nature' },
    { char: '💧', keywords: 'droplet', category: 'Nature' },
    { char: '🌊', keywords: 'water wave', category: 'Nature' },
    { char: '🪐', keywords: 'saturn, planet, space', category: 'Nature' },

    // Animals
    { char: '🐶', keywords: 'dog face', category: 'Animals' },
    { char: '🐱', keywords: 'cat, pet, animal', category: 'Animals' },
    { char: '🐰', keywords: 'rabbit, bunny, pet', category: 'Animals' },
    { char: '🐴', keywords: 'horse, animal', category: 'Animals' },
    { char: '🦄', keywords: 'unicorn, magic', category: 'Animals' },
    { char: '🐻', keywords: 'bear, animal', category: 'Animals' },
    { char: '🐼', keywords: 'panda, animal', category: 'Animals' },
    { char: '🐨', keywords: 'koala, animal', category: 'Animals' },
    { char: '🦁', keywords: 'lion, animal', category: 'Animals' },
    { char: '🐯', keywords: 'tiger, animal', category: 'Animals' },
    { char: '🐮', keywords: 'cow, animal', category: 'Animals' },
    { char: '🐷', keywords: 'pig, animal', category: 'Animals' },
    { char: '🐗', keywords: 'boar', category: 'Animals' },
    { char: '🐭', keywords: 'mouse', category: 'Animals' },
    { char: '🐹', keywords: 'hamster', category: 'Animals' },
    { char: '🦊', keywords: 'fox', category: 'Animals' },
    { char: '🐽', keywords: 'pig nose', category: 'Animals' },
    { char: '🐸', keywords: 'frog face', category: 'Animals' },
    { char: '🐵', keywords: 'monkey face', category: 'Animals' },
    { char: '🙈', keywords: 'see-no-evil monkey', category: 'Animals' },
    { char: '🙉', keywords: 'hear-no-evil monkey', category: 'Animals' },
    { char: '🙊', keywords: 'speak-no-evil monkey', category: 'Animals' },
    { char: '🐒', keywords: 'monkey', category: 'Animals' },
    { char: '🐔', keywords: 'chicken', category: 'Animals' },
    { char: '🐧', keywords: 'penguin', category: 'Animals' },
    { char: '🐦', keywords: 'bird', category: 'Animals' },
    { char: '🐤', keywords: 'baby chick', category: 'Animals' },
    { char: '🐣', keywords: 'hatching chick', category: 'Animals' },
    { char: '🐥', keywords: 'front-facing baby chick', category: 'Animals' },
    { char: '🦆', keywords: 'duck', category: 'Animals' },
    { char: '🦅', keywords: 'eagle', category: 'Animals' },
    { char: '🦉', keywords: 'owl', category: 'Animals' },
    { char: '🦇', keywords: 'bat', category: 'Animals' },
    { char: '🐺', keywords: 'wolf', category: 'Animals' },
    { char: '🐝', keywords: 'honeybee', category: 'Animals' },
    { char: '🐛', keywords: 'bug', category: 'Animals' },
    { char: '🦋', keywords: 'butterfly', category: 'Animals' },
    { char: '🐌', keywords: 'snail', category: 'Animals' },
    { char: '🐞', keywords: 'lady beetle', category: 'Animals' },
    { char: '🐜', keywords: 'ant', category: 'Animals' },
    { char: '🦗', keywords: 'cricket', category: 'Animals' },
    { char: '🕷️', keywords: 'spider', category: 'Animals' },
    { char: '🕸️', keywords: 'spider web', category: 'Animals' },
    { char: '🦂', keywords: 'scorpion', category: 'Animals' },
    { char: '🦟', keywords: 'mosquito', category: 'Animals' },
    { char: '🦠', keywords: 'microbe', category: 'Animals' },
    { char: '🐢', keywords: 'turtle', category: 'Animals' },
    { char: '🐍', keywords: 'snake', category: 'Animals' },
    { char: '🦎', keywords: 'lizard', category: 'Animals' },
    { char: '🦖', keywords: 't-rex', category: 'Animals' },
    { char: '🦕', keywords: 'sauropod', category: 'Animals' },
    { char: '🐙', keywords: 'octopus', category: 'Animals' },
    { char: '🦑', keywords: 'squid', category: 'Animals' },
    { char: '🦐', keywords: 'shrimp', category: 'Animals' },
    { char: '🦞', keywords: 'lobster', category: 'Animals' },
    { char: '🦀', keywords: 'crab', category: 'Animals' },
    { char: '🐡', keywords: 'blowfish', category: 'Animals' },
    { char: '🐠', keywords: 'tropical fish', category: 'Animals' },
    { char: '🐟', keywords: 'fish', category: 'Animals' },
    { char: '🐬', keywords: 'dolphin', category: 'Animals' },
    { char: '🐳', keywords: 'spouting whale', category: 'Animals' },
    { char: '🐋', keywords: 'whale', category: 'Animals' },
    { char: '🦈', keywords: 'shark', category: 'Animals' },
    { char: '🐊', keywords: 'crocodile', category: 'Animals' },
    { char: '🐅', keywords: 'tiger', category: 'Animals' },
    { char: '🐆', keywords: 'leopard', category: 'Animals' },
    { char: '🦓', keywords: 'zebra', category: 'Animals' },
    { char: '🦍', keywords: 'gorilla', category: 'Animals' },
    { char: '🦧', keywords: 'orangutan', category: 'Animals' },
    { char: '🐘', keywords: 'elephant', category: 'Animals' },
    { char: '🦛', keywords: 'hippopotamus', category: 'Animals' },
    { char: '🦏', keywords: 'rhinoceros', category: 'Animals' },
    { char: '🐪', keywords: 'camel', category: 'Animals' },
    { char: '🐫', keywords: 'two-hump camel', category: 'Animals' },
    { char: '🦒', keywords: 'giraffe', category: 'Animals' },
    { char: '🦘', keywords: 'kangaroo', category: 'Animals' },
    { char: '🦬', keywords: 'bison', category: 'Animals' },
    { char: '🐃', keywords: 'water buffalo', category: 'Animals' },
    { char: '🐂', keywords: 'ox', category: 'Animals' },
    { char: '🐄', keywords: 'cow', category: 'Animals' },
    { char: '🐎', keywords: 'horse', category: 'Animals' },
    { char: '🐖', keywords: 'pig', category: 'Animals' },
    { char: '🐏', keywords: 'ram', category: 'Animals' },
    { char: '🐑', keywords: 'ewe', category: 'Animals' },
    { char: '🐐', keywords: 'goat', category: 'Animals' },
    { char: '🦌', keywords: 'deer', category: 'Animals' },
    { char: '🐕', keywords: 'dog', category: 'Animals' },
    { char: '🐩', keywords: 'poodle', category: 'Animals' },
    { char: '🦮', keywords: 'guide dog', category: 'Animals' },
    { char: '🐕‍🦺', keywords: 'service dog', category: 'Animals' },
    { char: '🐈', keywords: 'cat', category: 'Animals' },
    { char: '🐈‍⬛', keywords: 'black cat', category: 'Animals' },
    { char: '🐓', keywords: 'rooster', category: 'Animals' },
    { char: '🦃', keywords: 'turkey', category: 'Animals' },
    { char: '🦚', keywords: 'peacock', category: 'Animals' },
    { char: '🦜', keywords: 'parrot', category: 'Animals' },
    { char: '🦢', keywords: 'swan', category: 'Animals' },
    { char: '🦩', keywords: 'flamingo', category: 'Animals' },
    { char: '🕊️', keywords: 'dove', category: 'Animals' },
    { char: '🦝', keywords: 'raccoon', category: 'Animals' },
    { char: '🦨', keywords: 'skunk', category: 'Animals' },
    { char: '🦡', keywords: 'badger', category: 'Animals' },
    { char: '🦦', keywords: 'otter', category: 'Animals' },
    { char: '🦥', keywords: 'sloth', category: 'Animals' },
    { char: '🐁', keywords: 'mouse', category: 'Animals' },
    { char: '🐀', keywords: 'rat', category: 'Animals' },
    { char: '🐿️', keywords: 'chipmunk', category: 'Animals' },
    { char: '🦔', keywords: 'hedgehog', category: 'Animals' },
    { char: '🐾', keywords: 'paw prints', category: 'Animals' },
    { char: '🐉', keywords: 'dragon', category: 'Animals' },
    { char: '🐲', keywords: 'dragon face', category: 'Animals' },

    // Symbols
    { char: '❤️', keywords: 'heart, love, red, like, romance', category: 'Symbols' },
    { char: '🧡', keywords: 'heart, love, orange, like', category: 'Symbols' },
    { char: '💛', keywords: 'heart, love, yellow, like, friendship', category: 'Symbols' },
    { char: '💚', keywords: 'heart, love, green, like, nature', category: 'Symbols' },
    { char: '💙', keywords: 'heart, love, blue, like, peace', category: 'Symbols' },
    { char: '💜', keywords: 'heart, love, purple, like', category: 'Symbols' },
    { char: '🖤', keywords: 'heart, love, black, sorrow', category: 'Symbols' },
    { char: '🤍', keywords: 'heart, love, white, pure', category: 'Symbols' },
    { char: '🤎', keywords: 'heart, love, brown', category: 'Symbols' },
    { char: '💔', keywords: 'heart, break, broken, sad, love', category: 'Symbols' },
    { char: '❣️', keywords: 'heart, exclamation, love, punctuation', category: 'Symbols' },
    { char: '💕', keywords: 'hearts, love, two, pink, romance', category: 'Symbols' },
    { char: '💞', keywords: 'hearts, revolving, love, pink', category: 'Symbols' },
    { char: '💓', keywords: 'heart, beating, love, pink, pulse', category: 'Symbols' },
    { char: '💗', keywords: 'heart, growing, love, pink', category: 'Symbols' },
    { char: '💖', keywords: 'heart, sparkle, love, pink, star', category: 'Symbols' },
    { char: '💟', keywords: 'heart, decoration, love, purple, square', category: 'Symbols' },
    { char: '☮️', keywords: 'peace, symbol, sign, hippie', category: 'Symbols' },
    { char: '✝️', keywords: 'cross, christian, religion, symbol', category: 'Symbols' },
    { char: '☪️', keywords: 'star and crescent, muslim, islam, religion, symbol', category: 'Symbols' },
    { char: '🕉️', keywords: 'om, hindu, religion, symbol, yoga', category: 'Symbols' },
    { char: '✡️', keywords: 'star of david, jewish, judaism, religion, symbol', category: 'Symbols' },
    { char: '☸️', keywords: 'wheel of dharma, buddhist, religion, symbol', category: 'Symbols' },
    { char: '☯️', keywords: 'yin yang, taoist, symbol, balance', category: 'Symbols' },
    { char: '♻️', keywords: 'recycle, symbol, green, environment', category: 'Symbols' },
    { char: '⚠️', keywords: 'warning, sign, symbol, danger, alert', category: 'Symbols' },
    { char: '🚫', keywords: 'prohibited, no, ban, stop, sign', category: 'Symbols' },
    { char: '✅', keywords: 'check, mark, green, yes, done, correct', category: 'Symbols' },
    { char: '❌', keywords: 'x, cross, red, no, wrong, stop', category: 'Symbols' },
    { char: '💯', keywords: '100, score, perfect, percent', category: 'Symbols' },
    { char: '💲', keywords: 'dollar, money, sign, currency', category: 'Symbols' },

    // Objects
    { char: '💡', keywords: 'bulb, light, idea, electricity, lamp', category: 'Objects' },
    { char: '💰', keywords: 'bag, money, dollar, cash, wealth, rich', category: 'Objects' },
    { char: '💵', keywords: 'bill, money, dollar, cash, currency', category: 'Objects' },
    { char: '💳', keywords: 'card, credit, money, pay, bank', category: 'Objects' },
    { char: '💎', keywords: 'gem, diamond, jewel, stone, expensive', category: 'Objects' },
    { char: '🔑', keywords: 'key, lock, door, password, secure', category: 'Objects' },
    { char: '🔒', keywords: 'lock, closed, secure, padlock', category: 'Objects' },
    { char: '🔓', keywords: 'unlock, open, padlock', category: 'Objects' },
    { char: '🔨', keywords: 'hammer, tool, build, fix, construction', category: 'Objects' },
    { char: '🔧', keywords: 'wrench, tool, fix, mechanic', category: 'Objects' },
    { char: '🧲', keywords: 'magnet, attraction, physics, tool', category: 'Objects' },
    { char: '🔫', keywords: 'pistol, gun, weapon, water, toy', category: 'Objects' },
    { char: '💣', keywords: 'bomb, explode, weapon, boom', category: 'Objects' },
    { char: '🔪', keywords: 'knife, kitchen, weapon, cut, cook', category: 'Objects' },
    { char: '🛡️', keywords: 'shield, protect, defense, armor', category: 'Objects' },
    { char: '🔮', keywords: 'crystal ball, magic, fortune, future', category: 'Objects' },
    { char: '📱', keywords: 'phone, mobile, cell, call, tech', category: 'Objects' },
    { char: '📷', keywords: 'camera, photo, picture, image, photography', category: 'Objects' },
    { char: '📺', keywords: 'tv, television, screen, video, show', category: 'Objects' },
    { char: '🕰️', keywords: 'clock, time, watch, antique', category: 'Objects' },
    { char: '⏰', keywords: 'alarm, clock, time, wake', category: 'Objects' },
    { char: '⏳', keywords: 'hourglass, time, sand, timer, wait', category: 'Objects' },
    { char: '🕶️', keywords: 'sunglasses, glasses, cool, sun, fashion', category: 'Objects' },
    { char: '👓', keywords: 'glasses, vision, eye, fashion', category: 'Objects' },
    { char: '🧢', keywords: 'cap, hat, baseball, fashion', category: 'Objects' },
    { char: '👑', keywords: 'crown, king, queen, royal, royalty', category: 'Objects' },
    { char: '💄', keywords: 'lipstick, makeup, beauty, fashion, cosmetics', category: 'Objects' },

    // People
    { char: '😀', keywords: 'smile, happy, face, grin', category: 'People' },
    { char: '😂', keywords: 'joy, laugh, cry, tears, funny, face', category: 'People' },
    { char: '😍', keywords: 'love, heart, eyes, face, crush', category: 'People' },
    { char: '🤔', keywords: 'think, face, wonder, question', category: 'People' },
    { char: '😭', keywords: 'cry, sad, tears, face, upset', category: 'People' },
    { char: '😡', keywords: 'angry, mad, face, red, rage', category: 'People' },
    { char: '👍', keywords: 'thumbs up, like, yes, good, hand, approve', category: 'People' },
    { char: '👎', keywords: 'thumbs down, dislike, no, bad, hand, disapprove', category: 'People' },
    { char: '👋', keywords: 'wave, hand, hello, goodbye, hi', category: 'People' },
    { char: '🙏', keywords: 'pray, hands, please, thank you, namaste', category: 'People' },
    { char: '🤝', keywords: 'handshake, deal, agree, meeting, hands', category: 'People' },
    { char: '👀', keywords: 'eyes, look, see, watch, peek', category: 'People' },
    { char: '💀', keywords: 'skull, death, dead, skeleton, halloween', category: 'People' },
    { char: '👽', keywords: 'alien, space, ufo, face, et', category: 'People' },
    { char: '🤖', keywords: 'robot, bot, tech, face, ai', category: 'People' },
    { char: '💩', keywords: 'poop, pile, shit, funny', category: 'People' }
];
